config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/find_closest_to/:id' => 'welcome#find_closest', as: :find_closest_news

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :data_sources
end

app/models/data_source.rb
class DataSource < ActiveRecord::Base
  belongs_to :category

  has_many :news
end

app/models/news.rb
class News < ActiveRecord::Base
  has_many :news_topics
  has_many :topics, through: :news_topics

  belongs_to :data_source
end

app/models/news_topic.rb
class NewsTopic < ActiveRecord::Base
  belongs_to :news
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :news_topics
  has_many :news, through: :news_topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :news_init, only: [:index, :find_closest]


  def index
    if params[:news_id]
      @news_id = params[:news_id]
    else
      ids = @news.pluck(:id)
      @news_id = Random.new.rand(ids.count - 1)
      while @news.find(ids[@news_id]).nil? do
        @news_id = Random.new.rand(ids.count - 1)
      end
    end

    find_closest(@news_id)
  end

  def find_closest(news_id = params[:id])
    require File.expand_path("../../../app/entities/analyser.rb", __FILE__)

    @news_id = news_id
    begin
      @base_news = @news.find(@news_id)
    rescue => error
      ids = @news.pluck(:id)
      @news_id = Random.new.rand(ids.count - 1)
      while @news.find(ids[@news_id]).nil? do
        @news_id = Random.new.rand(ids.count - 1)
      end
      @base_news = @news.find(ids[@news_id])
    end

    @closest_to_it = []
    @news.each{ |one_news|
      difference = solv_similarity(@base_news, one_news)
      @closest_to_it << [one_news, difference]
    }
    @closest_to_it.sort! { |x, y| x[1] <=> y[1] }
    @closest_to_it = @closest_to_it[1..5]

    respond_to do |format|
      format.html { render :index, news_id: news_id }
      format.json { render json: @closest_to_it }
      format.xml  { render xml: @closest_to_it }
    end
  end

  private

  def news_init
    @news = News.where.not(text: nil)
    @data_sources = DataSource.all
  end

  def solv_similarity(base_news, solving_news)
    base_news_words     =  base_news.text.split(' ') + base_news.description.split(' ') + base_news.title.split(' ')
    solving_news_words  =  solving_news.text.split(' ') + solving_news.description.split(' ') + solving_news.title.split(' ')

    base_news_abbrs     =  base_news_words.select{|word| word.index(/[A-Z]/) }
    solving_news_abbrs  =  solving_news_words.select{|word| word.index(/[A-Z]/) }

    difference = (base_news_abbrs - solving_news_abbrs).count
    difference += (base_news_words - solving_news_words).count.to_f / base_news_words.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsAgregator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.haml
.title
  %h1= link_to "News channel", root_path
  %hr
  .item-text= link_to @base_news.title, @base_news.link
  %ol
    - @closest_to_it.each do |item|
      %li= link_to item[0].title, "##{item[0].id}"
      %hr
      = item[1]
      %hr
      = link_to "find closest to me", find_closest_news_path(item[0].id)
      %hr
      %hr
  %hr
- @closest_to_it.each do |one_news, _|
  .item{:id => one_news.id}
    = link_to "#{one_news.id} # #{one_news.title} # #{one_news.data_source.name}", one_news.link, class: "item-title"
    %hr
    = link_to "find closest to me", find_closest_news_path(one_news.id)
    %hr
    .item-description= one_news.description.html_safe
    .item-text= one_news.text.html_safe
    %hr